# Generated by Django 3.1.7 on 2021-02-25 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee_cap',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='comment',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='expectations',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='future',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='likely',
            field=models.IntegerField(choices=[(1, 'Very Unlikely'), (2, 'Somewhat Unlikely'), (3, 'Neutral'), (4, 'Somewhat Likely'), (5, 'Very Likely')], default=1),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='overall',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='satisfaction',
            field=models.IntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], default=1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orgfile',
            name='empty_form',
            field=models.FileField(upload_to='empty_form'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='filled_form',
            field=models.FileField(upload_to='filled_form'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(default=True)),
                ('text', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
