# Generated by Django 3.1.2 on 2020-10-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cause_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause',
            old_name='cause',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='desc',
            new_name='description',
        ),
    ]
