# Generated by Django 3.1.2 on 2020-11-02 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_faq_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='index',
        ),
    ]
