# Generated by Django 3.1.2 on 2020-11-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_faq_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization'),
        ),
    ]
